### ISSUE TITLE
ReDoS on link regex

### ISSUE THREAD

**Issue by night** [Khan/simple-markdown#29]
The regex for the `link` rule is subject to DoS when there is a malformed link.

Working repro:

 ```
SimpleMarkdown.defaultBlockParse('[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n[+test)[]\n');
```

**Comment by ariabuckles** [comment]
Sorry for the delay; I've spent the past several months trying to bring a startup to launch.

Yikes! This looks like a real bug, thanks for pointing it out and I'll look into it.

**Comment by ariabuckles** [comment]
Figured out the issue; I'll have a fix for this out by monday. Sorry for the month lag D:

**Comment by ariabuckles** [comment]
Hi again!

This is fixed in version 0.2.2 (on npm), which is now out on npm.

I also reworked my bold/italic nested parsing solution so that it's backwards compatible, and released that as 0.3.0 (which includes 0.2.2/the fix for this issue). This lets simple-markdown correctly parse `***nested* bold and italics**`. This should just work (no breaking changes), but it *is* a lot of code changed. So if you'd be interested in testing that bold/italic/your custom rules work and letting me know if you run any problems, I'd love to fix them.

If this isn't a good time to test a more significant change, just updating to 0.2.2 fixes just this issue.

Thanks for your work on discord & for letting me know about simple-markdown issues~!

**Comment by night** [comment]
@ariabuckles thanks for your continued support of this module! we definitely exploit simple-markdown to the best of its ability and it's quite great for what it does. this week i will bump the version and throw it onto canary if things look alright locally (canary is our cutting edge public build that people are eager to try and report bugs for). i'll be sure to report any issues encountered 🤞

**Comment by ariabuckles** [comment]
Awesome, thanks @night! I'm happy it's been useful to you :D
