### ISSUE TITLE
Why the extra \n?

### ISSUE THREAD

**Issue by Jhonte** [Khan/simple-markdown#30]
Stumbled upon an issue with headings here https://github.com/Benjamin-Dobell/react-native-markdown-view/issues/2  that is based on simple-markdown.

Have only looked briefly into the code, but what's the reason for the last `\n` here?
https://github.com/Khan/simple-markdown/blob/master/simple-markdown.js#L558

Do you parse the whole text at once, can this be another solution?
http://regexr.com/3gc2f  or simply `/^(#{1,6})([^\n]*)/gm`?

So that you don't need to have an extra line break after a `#`.  Can't find any specification for markdown that says you need to specify this extra line break?  Please enlighten us @ariabuckles :)

**Comment by evan-scott-zocdoc** [comment]
I ended up using

```
/^(#{1,6})([^\n]+)/;
```

**Comment by ariabuckles** [comment]
Hi! Sorry for the delay! Been busy trying to get a startup to 1.0 >_<`

The reason for the extra newline is that all block rules in simple-markdown require a blank line between the next block element. This makes the grammar more consistent, and makes parsing simpler. And if you need to write a really long heading, you can just wrap it onto the next line like
any other block rule.

That said, there is one sort-of-exception: link definitions (`[1]: http://example.com`), which are allowed to be listed on consecutive lines (it's not a true exception because the block of link definitions still needs a blank line after all definitions). So there is some precedent for breaking on a single line break, and it might be worth changing this rule for headings in the future. (This rule affects other elements too, and is harder to change for those elements, but it might be worth changing specifically for headings if those are what are causing people trouble.)

Meanwhile, you're more than welcome to use @evan-scott-zocdoc's suggested regex for headings if it's helpful! (Or to be a little closer to the source, `/^ *(#{1,6}) *([^\n]+?) *#* *(?:\n *)*\n/`

Here's how I'd make a parser with this:

```javascript
    var SimpleMarkdown = require("simple-markdown");
    var rules = Object.assign({}, SimpleMarkdown.defaultRules, {
        heading: Object.assign({}, SimpleMarkdown.defaultRules.heading, {
            match: SimpleMarkdown.blockRegex(/^ *(#{1,6}) *([^\n]+?) *#* *(?:\n *)*\n/),
        }),
    });

    var parser = SimpleMarkdown.parserFor(rules);
    var reactOutput = SimpleMarkdown.reactFor(SimpleMarkdown.ruleOutput(rules, 'react'));

    var reactFromMarkdown = function(source) {
        // Many rules require content to end in \n\n to be interpreted
        // as a block, so we auto-append it to our source input.
        var blockSource = source + "\n\n";
        var parseTree = parser(blockSource, {inline: false});
        return reactOutput(parseTree);
    };
```

Based on the thread in https://github.com/Benjamin-Dobell/react-native-markdown-view/issues/2 , @Benjamin-Dobell seems like he'd prefer a single linebreak for headings, so I'll open a PR on https://github.com/Benjamin-Dobell/react-native-markdown-view with the above change.

Best,
Aria

**Comment by ariabuckles** [comment]
I'm going to close this as the original react-native-markdown-view issue has a PR open to fix the issue for them.

I said this on that comment too, but also putting this here for anyone following this thread: I'm going to hold off from addressing this in simple-markdown immediately, as I want to make sure it doesn't break any existing use cases or misalign with simple-markdown's philosophy too much, but I am definitely open to considering this in the root project after a little while if it's a major pain point.

In the mean time, anyone building something with simple-markdown should be able to replace the regex using the extension API above, if they would like that behaviour <3.

Thanks for bringing this up!

**Comment by Jhonte** [comment]
Thanks for fixing!   

I noticed that I can't use the syntax other way around now :)  But will take it up in react-native-markdown-view.

Example:
AnyText
#Title
