### ISSUE TITLE
Why paragraphs are rendered with divs?

### ISSUE THREAD

**Issue by sapegin** [Khan/simple-markdown#40]
It seems very unusual in comparison to other libraries. Would be nice to have at least a comment:

https://github.com/Khan/simple-markdown/blob/7627d864445616b6c749399bac2f64e3185a5434/simple-markdown.js#L1049-L1061

**Comment by ariabuckles** [comment]
Hi!

It renders divs with `class="paragraph"` because there are [odd browser rules about what may and may not be rendered inside a `p` tag][1]. The project I initially wrote this for had several elements that would run into that issue, and that issue causes strange behaviour in react, because the browser moves block elements that react renders inside paragraphs. Using a `div` gets around these rules, and prevents simple-markdown extensions from breaking simple-markdown core if they render a block inside a paragraph.

[1]: https://stackoverflow.com/questions/8397852/why-p-tag-cant-contain-div-tag-inside-it

It is an odd choice, and should probably be documented. As you've hopefully found, it should be easy to make an extension which just changes the paragraph rule to output a `p`.

```
var rules = Object.assign({}, SimpleMarkdown.defaultRules, {
    paragraph: Object.assign({}, SimpleMarkdown.defaultRules.paragraph, {
        react: function(node, output, state) {
            return <p key={state.key}>{output(node.content, state)}</p>;
        },
    },
});
```

**Comment by sapegin** [comment]
Yeah, I have a PR with this example: #41 ;-)

**Comment by ariabuckles** [comment]
oh, thanks! I'm still working my way through all the PRs and issues :).
