### ISSUE TITLE
Hash tags for headers don't work if the header is followed by regular text on a new line

### ISSUE THREAD

**Issue by maynardewm** [Khan/simple-markdown#54]
if I have the following:

```
#test
test
```

The parser fails to turn the header text into a title. The following doesn't work either:

```
#test#
test
```

```
test
#test
```

It only works with the following:
````
#test
````
```
#test

test
```

**Comment by ariabuckles** [comment]
Hi @maynardewm !

This is by design. To simplify the various parsing rules, all block-level grouping elements (paragraphs, lists, blockquotes, etc.) must be separated by an empty line, because otherwise, most markdown contexts would make the following line a part of the same block.

Thankfully, you can write a rule to change this behaviour:

```javascript
    var SimpleMarkdown = require("simple-markdown");
    var rules = Object.assign({}, SimpleMarkdown.defaultRules, {
        heading: Object.assign({}, SimpleMarkdown.defaultRules.heading, {
            match: SimpleMarkdown.blockRegex(/^ *(#{1,6}) *([^\n]+?) *#* *(?:\n *)*\n/),
        }),
    });

    var parser = SimpleMarkdown.parserFor(rules);
    var output = SimpleMarkdown.outputFor(rules, 'react');

    var reactFromMarkdown = function(source) {
        // Many rules require content to end in \n\n to be interpreted
        // as a block, so we auto-append it to our source input.
        var blockSource = source + "\n\n";
        var parseTree = parser(blockSource, {inline: false});
        return output(parseTree);
    };
```

This comes up somewhat frequently for headings, so for v1.0 i might consider making the above change the default, but only for headings.

**Comment by maynardewm** [comment]
Thank you for the reply! This took care of every situation except the following:

```
test
#test
```

**Comment by ariabuckles** [comment]
I'm glad that solved some of the issues!

This last case is because that's all being parsed as a paragraph, since there's not a blank line between the paragraph and the heading.

To be honest, it's hard to solve this issue in general in simple-markdown right now, as it complicates all the rules significantly (they all have to know about other block level rules that may start a new block). Because of this, and simple-markdown's focus on simplicity over compatibility, I don't intend to change this short term (but long-term I have some ideas).

The following would help in this specific case, but note that if the preceding `test` was a bulleted list, or some other block element (blockquote, etc), then you'd have to make the below modifications to those rules in addition to the paragraph rule.

```javascript
    var SimpleMarkdown = require("simple-markdown");
    var rules = Object.assign({}, SimpleMarkdown.defaultRules, {
        heading: Object.assign({}, SimpleMarkdown.defaultRules.heading, {
            match: SimpleMarkdown.blockRegex(/^ *(#{1,6}) *([^\n]+?) *#* *(?:\n *)*\n/),
        }),
        paragraph: Object.assign({}, SimpleMarkdown.defaultRules.paragraph, {
            match: SimpleMarkdown.blockRegex(/^((?:[^\n]|\n(?! *\n))+?)(?:\n *?)+(?:\n|(?=#))/),
        }),
    });

    var parser = SimpleMarkdown.parserFor(rules);
    var output = SimpleMarkdown.outputFor(rules, 'react');

    var reactFromMarkdown = function(source) {
        // Many rules require content to end in \n\n to be interpreted
        // as a block, so we auto-append it to our source input.
        var blockSource = source + "\n\n";
        var parseTree = parser(blockSource, {inline: false});
        return output(parseTree);
    };
```

**Comment by maynardewm** [comment]
Thank you so much, this works well, we can live with the block element issue for now. Thanks for all of your help explaining how to resolve this!

**Comment by ariabuckles** [comment]
Great, I'm glad it helped! thanks @maynardewm!

**Comment by ardeaf** [comment]
Hi @ariabuckles, what did you mean by this:
>The following would help in this specific case, but note that if the preceding test was a bulleted list, or some other block element (blockquote, etc), then you'd have to make the below modifications to those rules in addition to the paragraph rule.

Is this because all the other block elements in the defaultRules assume a blank line between preceding paragraphs before they will be matched? And if we wanted to not assume a blank line, we'd have to modify all of the block elements defaultRules match properties?

Is there a big problem with doing that that made you intentionally design the rules to assume a blank line before matching a block element regex?
