### ISSUE TITLE
Not parsing more than one rule

### ISSUE THREAD

**Issue by YouTwitFace** [Khan/simple-markdown#65]
I added custom rules and it only parses the first match. It seems to be a problem with my rules because it works with the default rules.

The code is [here](https://gist.github.com/12125b6fdf5c108e3adf2f031cd3babe) and if anyone can help find the problem, that'd be appreciated.

**Comment by ariabuckles** [comment]
Hi @YouTwitFace! Sorry for not getting back to this in March! Work was quite busy this last year.

Did you find a resolution to this, or would it still be helpful if I take a look?

**Comment by YouTwitFace** [comment]
I didn't find a solution yet. It would be very helpful if you can give me a hand.

**Comment by ariabuckles** [comment]
Sorry about that!

It looks like your `text` rule is capturing too much of the input, because it doesn't have any stopping conditions. The default text rule stops on any special characters, so using the default text rule's regex/match function should solve that. I also noticed your `em` and `strong` rules don't have the more recent quality/precedence changes, which you can make use of by extending those rules as well.

Here's a forked gist with those changes: https://gist.github.com/ariabuckles/3eb8dcba96df2852d8fc3b38e280744d

(And here's the gist changes: https://gist.github.com/ariabuckles/3eb8dcba96df2852d8fc3b38e280744d/revisions )

**Comment by YouTwitFace** [comment]
Thanks, I'll have a look when I can.

**Comment by ariabuckles** [comment]
no rush :). Let me know if that's still having problems whenever you do :).

**Comment by YouTwitFace** [comment]
It works, thanks. 👍
