### ISSUE TITLE
list error when it has '&' at the end of line

### ISSUE THREAD

**Issue by andangrd** [Khan/simple-markdown#81]
I'm getting an odd behavior of the parser, 
it marks this symbol `&` as a new paragraph under the `list`.

```
- test1 &
- test2
- test3
```

result :
- test1
  &
- test2
- test3

Not sure either, but I think the problem is on regex for parsing `list`
does anyone have any idea for this issue, please?

**Comment by ariabuckles** [comment]
Sorry for the late response!

This usually happens because punctuation causes the text nodes to be split up, and the styling of the system you're in isn't treating those adjacent nodes as inline text.

I made a change to simple-markdown a while back that makes this easier to avoid: if you use `ruleOutput` rather than `reactFor(ruleOutput())`, it should join adjacent text nodes and avoid this problem:

Instead of:

```javascript
var reactOutput = SimpleMarkdown.reactFor(SimpleMarkdown.ruleOutput(rules, 'react'));
```

Make sure you're on a recent version of simple-markdown (0.4.0+), and replace it with:

```
var reactOutput = SimpleMarkdown.outputFor(rules, 'react');
```

And 🤞 that might fix your problem for you.

If that doesn't help and you have some sample code to show how you're using simple-markdown, I might be able to dig a big deeper.

**Comment by andangrd** [comment]
perfect...
thanks @ariabuckles
